# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42bdf8d35d7859bf1c6f8152593384804b34cac1ad5e310a77e702f13cb58aaaf1f8384fc2cf2eb8702cb296e72065bbfb0c39fa50684a6ec5387fb46bf4084d

test:
  secret_key_base: 6d1e85f0913433ecc9ed2fe08d6b96ac18e5b58ec2b4766108267f087812e0741db17e2285e515d908739c94fe17d353af027e053f994b92524a9b134e6e9dd5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
